# Generated by Django 6.0.4 on 2026-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=100)),
                ('vehicle_count', models.IntegerField()),
                ('emergency_vehicle', models.BooleanField(default=False)),
                ('signal_status', models.CharField(default='RED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
