# Generated by Django 6.0.4 on 2026-05-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficdata',
            name='green_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='traffic_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
    ]
